### ISSUE TITLE
Issue starting watch app

### ISSUE THREAD

**Issue by trentguillory** [hungtruong/Zswift#3]
Hey, thanks so much for creating this open-source app. It's the most thorough example of connectivity between an iOS app and watchOS companion I've found. 

I set out looking for examples when my own project continuously failed at the `startWatchApp` function of `healthStore`. So I thought I'd see how yours accomplished it!

Unfortunately, when running Zswift, this method also never completed successfully. The watch app continues to not launch at this point, despite being open and having all permissions granted. In fact, the callback never fires - even though it clearly fails (doesn't open app, doesn't return success=true) it doesn't provide an error either. 

Have you run into this issue before? Maybe there's something big I'm missing? Any help would be appreciated. 

Really cool recreation of Zswift. They should hire you. 😄

**Comment by hungtruong** [comment]
Oops, I think I never got an email for this issue. I just saw it now after a few years...

Anyway, that's cool, thanks for the props. I am not sure how to debug because it has been working for me for a while now. My best guess would be maybe there's some issues with entitlements with your developer account? Because that would probably be the only difference between my setup and yours? Not sure though cause it's been working for me. Sorry it took so long for me to respond!
